from ultralytics import YOLO

# 1. Load the pre-trained model (using the nano or small version for edge devices)
model = YOLO('yolov8n.pt')  # You can change 'n' to 's' or 'm' depending on your exact version

# 2. Train the model on your custom Master Dataset
print(" Starting YOLO Training...")
results = model.train(
    data='Master_Dataset/data.yaml',  # Path to the yaml file generated by merge.py
    epochs=50,                        # Number of training cycles 
    imgsz=640,                        # The 640x640 resolutio discussed!
    batch=16,                         # Number of images processed at once
    device=0,                         # Uses the GPU (Set to 'cpu' if no GPU)
    plots=True                        # Generates the confusion matrix and F1 curves automatically!
)
print(" YOLO Training Complete!")